# -*- coding: utf-8 -*-
"""predictionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4lSPtrHzznSb_1wrdI1BP6LKGnvTEYj
"""

import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Fungsi untuk preprocessing data baru
def preprocess_new_data(new_data, scaler):
    new_data.drop(['Over18'], axis=1, inplace=True)
    new_data.drop(['StandardHours'], axis=1, inplace=True)

    label_encoder = LabelEncoder()

    # Encode kolom kategorikal menggunakan LabelEncoder
    categorical_columns = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

    for col in categorical_columns:
        # Fit the LabelEncoder and transform the column
        new_data[col] = label_encoder.fit_transform(new_data[col])

    # Standarisasi fitur numerik
    numerical_features = new_data.select_dtypes(include=['int64', 'float64']).columns.tolist()

    new_data[numerical_features] = scaler.transform(new_data[numerical_features])

    return new_data

# Fungsi untuk melakukan prediksi
def predict_attrition(new_data, model, scaler):
    # Preprocessing data baru
    new_data_processed = preprocess_new_data(new_data, scaler)

    # Melakukan prediksi
    prediction = model.predict(new_data_processed)

    return prediction

# Memuat model yang sudah disimpan dan scaler/label encoder
model = joblib.load('/content/logistic_regression_model.pkl')
scaler = joblib.load('/content/scaler.pkl')
label_encoders = joblib.load('/content/label_encoders.pkl')

# Contoh data baru (misalnya data karyawan baru)
new_data = pd.DataFrame({
    'Age': [35],
    'BusinessTravel': ['Travel_Rarely'],
    'DailyRate': [1000],
    'Department': ['Research & Development'],
    'DistanceFromHome': [10],
    'Education': [3],
    'EducationField': ['Life Sciences'],
    'EnvironmentSatisfaction' : [2],
    'Gender': ['Male'],
    'HourlyRate': [50],
    'JobInvolvement': [3],
    'JobLevel': [2],
    'JobRole': ['Research Scientist'],
    'JobSatisfaction': [3],
    'MaritalStatus': ['Single'],
    'MonthlyIncome': [5000],
    'MonthlyRate': [15000],
    'NumCompaniesWorked': [5],
    'Over18': ['Y'],
    'OverTime': ['Yes'],
    'PercentSalaryHike': [10],
    'PerformanceRating': [3],
    'RelationshipSatisfaction': [3],
    'StandardHours': [80],
    'StockOptionLevel': [2],
    'TotalWorkingYears': [10],
    'TrainingTimesLastYear': [3],
    'WorkLifeBalance': [3],
    'YearsAtCompany': [5],
    'YearsInCurrentRole': [3],
    'YearsSinceLastPromotion': [2],
    'YearsWithCurrManager': [4]
})

# Memanggil fungsi prediksi
prediction = predict_attrition(new_data, model, scaler)

# Menampilkan hasil prediksi
if prediction[0] == 1:
    print("Karyawan ini diprediksi akan mengalami Attrition.")
else:
    print("Karyawan ini diprediksi tidak akan mengalami Attrition.")